#!/bin/bash

set -e

KEY=barth
INPUT=texts/paragraphs/

/Users/csb5t/projects/mallet/bin/mallet import-dir --input $INPUT --output models/full60/$KEY.mallet --keep-sequence --remove-stopwords
/Users/csb5t/projects/mallet/bin/mallet train-topics --input models/full60/$KEY.mallet --num-topics 60 --optimize-interval 10 --num-iterations 2000 \
	--output-model models/full60/$KEY.model --output-state models/full60/$KEY.state.gz --output-doc-topics models/full60/$KEY.doc.topics \
	--output-topic-keys models/full60/$KEY.keys \
  --topic-word-weights-file models/full60/$KEY.weights --word-topic-counts-file models/full60/$KEY.words
