#!/bin/bash

# Call it like this:
# PYTHONPATH=$(pwd) PATH=$(pwd)/scripts:$PATH ./scripts/classify_all

CORPUS=data/corpus.csv
RESULTS=logs/results.csv
if [ -f $RESULTS ]; then
    rm $RESULTS
fi

classify.py --corpus=$CORPUS --results=$RESULTS --feature-file=logs/features.log | tee logs/classify.log
classify.py --corpus=$CORPUS --results=$RESULTS --feature-file=logs/features-select.log --select-features=0.16 | tee logs/classify-select.log

classify.py --corpus=$CORPUS --results=$RESULTS --feature-file=logs/features-bigram.log --ngram-range=1-2 | tee logs/classify-bigram.log
classify.py --corpus=$CORPUS --results=$RESULTS --feature-file=logs/features-bigram-select.log --select-features=0.16 --ngram-range=1-2 | tee logs/classify-bigram-select.log

classify.py --corpus=$CORPUS --results=$RESULTS --feature-file=logs/features-trigram.log --ngram-range=1-3 | tee logs/classify-trigram.log
classify.py --corpus=$CORPUS --results=$RESULTS --feature-file=logs/features-trigram-select.log --select-features=0.16 --ngram-range=1-3 | tee logs/classify-trigram-select.log
